### ISSUE TITLE
Forge mod interop

### ISSUE THREAD

**Issue by zontreck** [ObsidianMC/Obsidian#150]
Similarly to #18, it would be interesting to see a feature which brings support for forge mods as well, not just bukkit/spigot plugins.

Now while those are in most cases, direct modifications of the codebase, perhaps it would be possible to bring support for features like RefinedStorage.

I request this feature because of the implications of a C# server being capable of being optimized far more than java. Which would give better garbage collection, and therefore less memory usage.

**Comment by Tides** [comment]
As much as I would like this, it'll most likely not happen due to the complexity of forge. And the same goes for #18 although it might be a bit easier for spigot/bukkit . I am going to make sure that it'll be fairly straightforward for plugins made through obsidian will be compatible and (recognized as a mod) with the forge client and whatever mod you'll want to "implement" on obsidian

**Comment by zontreck** [comment]
Well if plugins for Obsidian were able to be recognized as a Forge Mod, it would be fairly straightforward to actually write the serverside of a opensourced Java mod.

I can support that, i know forge is quite complex, so hopefully that would end up at least being a compromise.

**Comment by zontreck** [comment]
Is there a discord for this project? I would like to join so i don't flood the issues page with irrelevant posts. I'm looking at helping contribute to this project.

**Comment by Tides** [comment]
> Is there a discord for this project? I would like to join so i don't flood the issues page with irrelevant posts. I'm looking at helping contribute to this project.

https://discord.gg/gQBtqyXChu

**Comment by Tides** [comment]
Closing this as well 🙏🏼
