### ISSUE TITLE
Packet priority

### ISSUE THREAD

**Issue by Naamloos** [ObsidianMC/Obsidian#401]
When loading the overworld, the server seems to be very slow sending other packets as the queue is filled with world packets.

This means that when a player's render distance is set to something high, other packets don't seem to arrive until chunks have completed loading.

My idea here is to add priorities to packets (in one way or another) to ensure e.g. chunk packets get sent last and chat packets get sent immediately.

This would in theory improve the end-user experience since this means other players and entities wouldn't freeze up until the world finished loading all requested chunks.

**Comment by Naamloos** [comment]
I had come to this conclusion simply by the fact the server seemed to perform better when the render distance is set to 2 chunks

**Comment by Tides** [comment]
I think this has to do with world generation blocking the main server loop, I haven't opened an issue for it but I think moving it out and adding it as a hosted service the problem should probably get better

**Comment by Jonpro03** [comment]
At login, 7x7 chunks MUST be sent to the client before spawning the player (PlayerJoin). Failing to do so results in the client sitting at a loading screen until it times out and loads what it has.
This is also true of teleportation/dimension change, I think.
Will need a way to flag these chunks as highest priority, or otherwise wait until the client has all of the chunks it needs before spawning the player.

**Comment by Naamloos** [comment]
Great point, perhaps priority would be defined when sending instead of globally?

**Comment by Tides** [comment]
This is added in #403 but before I close 

> I had come to this conclusion simply by the fact the server seemed to perform better when the render distance is set to 2 chunks

Has this gotten any better?

**Comment by Tides** [comment]
Gonna close this as this is implemented and from my testing seems to no longer be a problem ~
